In [52]:
import torch
x = torch.ones(4, requires_grad=True)


In [53]:
print(x.data)


tensor([1., 1., 1., 1.])


In [55]:
x = torch.cat((x[:2].detach().clone(),x[2:]))
x

tensor([1., 1., 1., 1.], grad_fn=<CatBackward0>)

In [56]:
y = x + 2
y

tensor([3., 3., 3., 3.], grad_fn=<AddBackward0>)

In [57]:
y.backward(torch.ones(4), retain_graph=True)
# the retain_variables flag will prevent the internal buffers from being freed
print(x.grad)

None


/tmp/ipykernel_46177/3012729239.py:3: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:480.)
  print(x.grad)


In [58]:
gradient = torch.randn(4)


In [59]:
y.backward(gradient)


In [60]:
x

tensor([1., 1., 1., 1.], grad_fn=<CatBackward0>)

In [61]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([27., 27., 27., 27.], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [62]:
out.backward()
print(x.grad)

None


/tmp/ipykernel_46177/1047789322.py:2: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:480.)
  print(x.grad)


In [63]:
x

tensor([1., 1., 1., 1.], grad_fn=<CatBackward0>)