In [36]:
import torch
import os

In [37]:
st1 = torch.load('/data2/grbagwe/Projects/promptFCL/_outputs/ICCV/CIFAR100/10-task/Fed-CPrompt/vit/iid/models/repeat-2/task-1/class.pth')
st2 = torch.load('/data2/grbagwe/Projects/promptFCL/_outputs/ICCV/CIFAR100/10-task/Fed-CPrompt/vit/iid/models/repeat-2/task-2/class.pth')

In [38]:
st1['module.prompt.e_p_0'][i].shape

torch.Size([8, 768])

In [39]:
st1['module.prompt.e_p_0'][0][0], st2['module.prompt.e_p_0'][0][0]

(tensor([-1.3925e-02, -1.2478e-02, -7.3880e-03, -1.4464e-02, -1.1838e-02,
         -5.4355e-03,  1.8040e-03,  1.3897e-02, -3.9319e-03,  1.8435e-02,
          1.4423e-02,  2.1598e-04, -2.7866e-02,  8.0686e-03,  1.8753e-02,
          5.8629e-04,  3.5318e-03, -8.2637e-03,  9.7297e-03,  1.1388e-02,
         -1.1587e-03,  2.5943e-03,  1.7901e-02, -3.9231e-04,  6.3210e-04,
         -2.2880e-02, -9.6857e-03,  7.1413e-05, -6.3176e-03,  3.2530e-02,
         -1.4360e-02, -1.4927e-02, -7.9296e-03, -1.2650e-02,  6.9380e-03,
         -1.4861e-02, -9.6029e-03,  7.1438e-03, -4.2397e-03,  1.2571e-02,
          2.3487e-02, -2.9970e-02,  4.2748e-03, -2.0565e-02,  1.5540e-02,
         -9.8195e-03,  1.5704e-02,  1.1589e-02,  2.0632e-02,  1.1157e-02,
          1.0658e-02,  1.7440e-02, -3.0063e-02,  1.2373e-02, -1.3318e-03,
          1.0147e-02,  1.7961e-02, -6.5305e-03,  3.6216e-03, -3.0194e-02,
          1.7853e-02,  8.1470e-03, -1.6653e-03, -2.3485e-02,  2.9796e-02,
         -1.4681e-02,  3.9047e-03, -1.

In [82]:
for key in st1.keys():
    if 'prompt' not in key:
        print(key)

module.last.weight
module.last.bias
module.feat.cls_token
module.feat.pos_embed
module.feat.patch_embed.proj.weight
module.feat.patch_embed.proj.bias
module.feat.blocks.0.norm1.weight
module.feat.blocks.0.norm1.bias
module.feat.blocks.0.attn.qkv.weight
module.feat.blocks.0.attn.qkv.bias
module.feat.blocks.0.attn.proj.weight
module.feat.blocks.0.attn.proj.bias
module.feat.blocks.0.norm2.weight
module.feat.blocks.0.norm2.bias
module.feat.blocks.0.mlp.fc1.weight
module.feat.blocks.0.mlp.fc1.bias
module.feat.blocks.0.mlp.fc2.weight
module.feat.blocks.0.mlp.fc2.bias
module.feat.blocks.1.norm1.weight
module.feat.blocks.1.norm1.bias
module.feat.blocks.1.attn.qkv.weight
module.feat.blocks.1.attn.qkv.bias
module.feat.blocks.1.attn.proj.weight
module.feat.blocks.1.attn.proj.bias
module.feat.blocks.1.norm2.weight
module.feat.blocks.1.norm2.bias
module.feat.blocks.1.mlp.fc1.weight
module.feat.blocks.1.mlp.fc1.bias
module.feat.blocks.1.mlp.fc2.weight
module.feat.blocks.1.mlp.fc2.bias
module.feat.bl

In [69]:
e1 = st1['module.prompt.e_k_0'][:20]
e2 = st2['module.prompt.e_k_0'][:20]


In [62]:
def ortho_penalty(t):
    return ((t @t.T - torch.eye(t.shape[0]).cuda())**2)

In [72]:
ortho_penalty(e1.cuda())
# get diagonal of ortho penalty
ortho_penalty(e1.cuda()).diag()

tensor([1.8409e-04, 4.2276e-03, 3.3395e-04, 1.4277e-03, 4.2163e-03, 4.1600e-03,
        2.4484e-03, 9.3565e-04, 8.5083e-04, 9.3825e-04, 3.5527e-15, 1.4211e-14,
        0.0000e+00, 0.0000e+00, 1.4211e-14, 5.6843e-14, 3.5527e-15, 5.6843e-14,
        5.6843e-14, 1.2790e-13], device='cuda:0')

In [74]:
A = torch.tensor([[1,2],[1,2]])

In [76]:
A @ A.T

tensor([[5, 5],
        [5, 5]])

In [56]:
code_p = torch.load('/data2/grbagwe/Projects/promptFCL/_outputs/ICCV/CIFAR100/10-task/vit/coda-p_cifarfed_niid_0_1/models/repeat-1/task-2/class.pth')
e3 = code_p['module.prompt.e_k_0'][:20]

In [57]:
ortho_penalty(e3.cuda())

tensor(1.9510e-08, device='cuda:0')

In [42]:
# for i in range(100):
#     a = sum(sum(st1['module.prompt.e_p_0'][i] - st2['module.prompt.e_p_0'][i]))
#     # round a to 4 decimal places
    
#     print(a)

In [43]:
# for i in range(100):
#     a = sum(st1['module.last.weight'][i] - st2['module.last.weight'][i])
#     # round a to 4 decimal places
    
#     print(a)

In [7]:
st3 = torch.load('/data2/grbagwe/Projects/promptFCL/_outputs/ICCV/CIFAR100/10-task/fedMoon1/vit/coda-iid_fedMoon_aba/models/repeat-1/task-1/class.pth')

In [33]:
st3['module.prompt.e_p_0'][0][0], st2['module.prompt.e_p_0'][0][0]

tensor([-8.5843e-03, -3.3599e-03,  1.2942e-02, -1.3664e-02, -1.2111e-02,
        -1.1349e-02,  4.8244e-03, -1.0592e-02,  2.1661e-03,  1.4406e-02,
        -1.1578e-04,  1.9687e-02, -2.2002e-02,  1.4002e-03, -2.2599e-03,
        -1.1109e-02, -1.5257e-04,  1.3199e-02,  3.3863e-02,  1.1843e-02,
        -2.5647e-02, -8.7176e-03,  4.5859e-03,  8.2995e-03, -1.3179e-02,
        -3.1618e-03, -4.3002e-03, -7.9276e-03,  2.2441e-03, -5.2186e-03,
        -2.1366e-02, -1.4434e-02,  7.2190e-04, -5.8073e-03, -1.3740e-02,
        -9.0550e-03,  3.4068e-03, -4.5407e-03, -2.9088e-02, -2.5224e-03,
        -3.4188e-03,  1.0489e-02,  1.5611e-02,  5.2399e-03,  8.0229e-03,
        -7.0890e-03, -6.7209e-03,  9.2295e-03,  5.1297e-03, -2.3880e-02,
        -2.3231e-02,  1.0071e-02,  4.4583e-03,  1.1365e-02,  6.3238e-03,
        -5.5524e-04, -7.1558e-04,  3.5900e-03, -2.2951e-03,  7.4427e-03,
         1.8068e-02, -3.0602e-02, -4.8861e-03, -5.0274e-03, -1.8293e-02,
         1.2112e-02, -7.0065e-03, -1.2290e-02,  3.3

In [35]:
st1['module.feat.blocks.0.mlp.fc2.weight']

tensor([[ 2.7333e-02,  2.9605e-03,  4.9715e-04,  ...,  4.5406e-02,
         -3.1697e-03, -9.0844e-03],
        [-7.7757e-03,  1.7613e-02, -5.5463e-03,  ..., -8.6016e-03,
         -2.9693e-02,  1.7059e-02],
        [-1.3004e-03,  2.4648e-02,  4.6962e-03,  ..., -1.2538e-03,
         -9.7564e-05, -4.0829e-04],
        ...,
        [-1.4441e-02,  1.6398e-02, -3.3571e-02,  ..., -1.5621e-02,
          9.2722e-04, -1.4439e-02],
        [ 1.1654e-02, -2.7358e-03,  2.2031e-02,  ...,  3.5457e-02,
          4.6814e-03,  1.6768e-02],
        [-2.6262e-02,  3.8934e-03,  2.8341e-02,  ..., -7.6181e-03,
         -8.2380e-03,  1.4445e-02]])